#!/bin/bash
# TODO: Enable compression
./build_using_cmake.sh rocksdb "-DWITH_TESTS=OFF -DWITH_LZ4=OFF -DWITH_BZ2=OFF -DWITH_ZLIB=OFF -DWITH_ZSTD=OFF -DWITH_SNAPPY=OFF -DWITH_JEMALLOC=OFF -DCMAKE_INSTALL_LIBDIR=lib"
